import { REACT, REDUX, TAILWIND, FIRESTORE, JS, MANTINE, MOCKAPI, BOOTSTREP, HTML, CSS, GOLANG, ECHO, JWT, TESTIFY, POSTGRESQL, AWS, DOCKER } from './assets';

export const datas = [
  {
    title: 'EmpowerHR-App',
    deskripsi: '"Empower HR" is a software solution designed to make it easier to manage human resources within a company.',
    demo: '',
    github: 'https://github.com/Empower-HR/BE-Empower-HR',
    icons: [
      { name: 'Golang', img: GOLANG },
      { name: 'Echo', img: ECHO },
      { name: 'Jwt', img: JWT },
      { name: 'Unit Testing', img: TESTIFY },
      { name: 'PostgreSQL', img: POSTGRESQL },
      { name: 'AWS', img: AWS },
      { name: 'Docker', img: DOCKER },
    ],
  },
  {
    title: 'Ecommerce-App',
    deskripsi: 'Ecommerce App adalah sebuah aplikasi yang digunakan untuk memanajemen toko online.',
    demo: '',
    github: 'https://github.com/akbaralisyifa/K2-Project-Ecommerce',
    icons: [
      { name: 'Golang', img: GOLANG },
      { name: 'Echo', img: ECHO },
      { name: 'Jwt', img: JWT },
      { name: 'Unit Testing', img: TESTIFY },
      { name: 'PostgreSQL', img: POSTGRESQL },
    ],
  },
  {
    title: 'News-Apps',
    deskripsi: 'News Apps adalah sebuah aplikasi yang digunakan untuk berbagi cerita atau artikel.',
    demo: '',
    github: 'https://github.com/akbaralisyifa/News_Apps',
    icons: [
      { name: 'Golang', img: GOLANG },
      { name: 'Echo', img: ECHO },
      { name: 'Jwt', img: JWT },
      { name: 'Unit Testing', img: TESTIFY },
      { name: 'PostgreSQL', img: POSTGRESQL },
    ],
  },
  {
    title: 'Learning Golang',
    deskripsi: 'Kumpulan Tugas Immersive Program Backend Golang | Alterra Academy',
    demo: '',
    github: 'https://github.com/akbaralisyifa/ALTA-BE23-Muhammad-Akbar-Ali-Syifa',
    icons: [
      { name: 'Golang', img: GOLANG },
      { name: 'Echo', img: ECHO },
      { name: 'Jwt', img: JWT },
      { name: 'Unit Testing', img: TESTIFY },
      { name: 'PostgreSQL', img: POSTGRESQL },
    ],
  },
  {
    title: 'Netflix',
    deskripsi: 'Website Netflix yang menampilkan list film',
    demo: 'https://netflix-project-lemon.vercel.app/',
    github: 'https://github.com/akbaralisyifa/Netflix_Project',
    icons: [
      { name: 'React', img: REACT },
      { name: 'Tailwind', img: TAILWIND },
      { name: 'Firebase', img: FIRESTORE },
    ],
  },
  {
    title: 'Test Skills',
    deskripsi: 'Test Assessment Skills membuat tampilan dashboard sesuai dengan UI',
    demo: 'https://test-skill-dashboard.vercel.app',
    github: 'https://github.com/akbaralisyifa/Test_Dashboard',
    icons: [
      { name: 'React', img: REACT },
      { name: 'Tailwind', img: TAILWIND },
    ],
  },
  {
    title: 'MedKit',
    deskripsi: 'Website Penjualan Obat dengan memanfaatkan Redux, berintegrasi dengan Open AI, serta Memiliki Dashboard Admin',
    demo: 'https://medkit-gilt.vercel.app/',
    github: 'https://github.com/akbaralisyifa/medkit',
    icons: [
      { name: 'React', img: REACT },
      { name: 'Redux', img: REDUX },
      { name: 'Tailwind', img: TAILWIND },
      { name: 'Mantine', img: MANTINE },
      { name: 'MockAPI', img: MOCKAPI },
    ],
  },
  {
    title: 'Restfull API',
    deskripsi: ' Website yang memanfaatkan Resfull API menggunakan Axios untuk fetch data, dan memanfaatkan Authentication',
    demo: '',
    github: 'https://github.com/akbaralisyifa/react_muhammad-akbar-ali-syifa/tree/main/18_Restfull-API/praktikum',
    icons: [
      { name: 'React', img: REACT },
      { name: 'Redux', img: REDUX },
      { name: 'bootstrap', img: BOOTSTREP },
      { name: 'MockAPI', img: MOCKAPI },
    ],
  },
  {
    title: 'OpenAI',
    deskripsi: 'website yang berintegrasi dengan OpenAI',
    demo: '',
    github: 'https://github.com/akbaralisyifa/medkit',
    icons: [{ name: 'React', img: REACT }],
  },
  {
    title: 'Form React',
    deskripsi: 'Implementasi Form pada React JS',
    demo: '',
    github: 'https://github.com/akbaralisyifa/react_muhammad-akbar-ali-syifa/tree/main/15_React-Form/praktikum',
    icons: [{ name: 'React', img: REACT }],
  },
  {
    title: 'Restfull API',
    deskripsi: 'Implementasi Restfull API pada Javascript',
    demo: '',
    github: 'https://github.com/akbaralisyifa/restfull_API_Javascript',
    icons: [
      { name: 'HTML', img: HTML },
      { name: 'CSS', img: CSS },
      { name: 'Javascript', img: JS },
    ],
  },
  {
    title: 'Restfull API',
    deskripsi: 'Implementasi Restfull API pada Javascript',
    demo: '',
    github: 'https://github.com/akbaralisyifa/restfull_API_Javascript',
    icons: [
      { name: 'HTML', img: HTML },
      { name: 'CSS', img: CSS },
      { name: 'Javascript', img: JS },
    ],
  },
  {
    title: 'Todo App',
    deskripsi: 'Implementasi Todo App penggunakan webStorage',
    demo: '',
    github: 'https://github.com/akbaralisyifa/todoApp_WebStorage',
    icons: [
      { name: 'HTML', img: HTML },
      { name: 'CSS', img: CSS },
      { name: 'Javascript', img: JS },
    ],
  },
  {
    title: 'Portfolio V.1',
    deskripsi: 'Latihan Tailwind Css membuat sebuah website Portfolio',
    demo: 'https://akbaralisyifa.github.io/Portfolio/',
    github: 'https://github.com/akbaralisyifa/Portfolio',
    icons: [
      { name: 'HTML', img: HTML },
      { name: 'CSS', img: CSS },
      { name: 'Javascript', img: JS },
      { name: 'Tailwind', img: TAILWIND },
    ],
  },
];
